[package]
name = "k8s-metrics"
version = "0.2.0"
edition = "2021"
rust-version = "1.61"
description = "K8s Metrics API Resource definitions"
repository = "https://github.com/imp/k8s-metrics-rs"
license = "Apache-2.0"


[dependencies]
k8s-openapi = { version = "0.16", features = [] }
serde = { version = "1.0", features = ["derive"] }


[dev-dependencies]
k8s-openapi = { version = "0.16", features = ["v1_24"] }
serde_json = "1.0"

[package.metadata.docs.rs]
features = ["k8s-openapi/v1_24"]
